name: workflow for S3 Deploy Develop
on:
  push:
    branches:
      - develop
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      REACT_APP_API_URL: ${{secrets.REACT_APP_API_URL_DEV}}
      REACT_APP_ENV: ${{secrets.REACT_APP_ENV_DEV}}
      REACT_APP_SENTRY_DSN: ${{secrets.REACT_APP_SENTRY_DSN}}
      VITE_APP_API_URL: ${{secrets.VITE_APP_API_URL}}
      VITE_TOKEN: ${{secrets.VITE_TOKEN}}

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build dev
        run: npm run build

      - name: Deploy
        uses: reggionick/s3-deploy@v3
        with:
          folder: dist
          bucket: ${{ secrets.S3_BUCKET_DEV }}
          bucket-region: ${{secrets.DEFAULT_BUCKET_REGION}}
          dist-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID_DEV }}
          invalidation: /*
          delete-removed: true
          no-cache: true
          private: true
